disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - trailing_closure
  - identifier_name
  
included:
  - TestingDangerApp/ViewController.swift

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods/
  - Dependencies
  - Recovered References

opt_in_rules:
  - attributes
  - closure_parameter_position
  - closure_spacing
  - colon
  - empty_count
  - empty_enum_arguments
  - empty_parentheses_with_trailing_closure
  - file_header
  - first_where
  - for_where
  - force_cast
  - force_try
  - mark
  - multiline_parameters
  - nesting
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - statement_position
  - syntactic_sugar
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - type_name
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - weak_delegate
  - block_based_kvo
  - class_delegate_protocol
  - closure_body_length
  - closure_end_indentation
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  # - convenience_type
  - empty_string
  - explicit_enum_raw_values
  - explicit_init
  - implicitly_unwrapped_optional
  - literal_expression_end_indentation
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - override_in_extension
  # - private_action
  # - private_outlet
  - private_over_fileprivate
  - reduce_boolean
  - redundant_string_enum_value
  - redundant_type_annotation
  - sorted_imports
  - static_operator
  - switch_case_alignment
  - switch_case_on_newline
  # - toggle_bool
  - type_body_length
  - type_contents_order
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
  - unused_import
  - void_return

custom_rules:
  vertical_whitespace_opening_braces:
    included: ".*.swift"
    regex: '[{(\[][ \t]*\n[ \t]*\n'
    name: "Vertical Whitespace after Opening Braces"
    message: "Don't include vertical whitespace (empty line) after opening braces."
    severity: warning
  vertical_whitespace_closing_braces:
    included: ".*.swift"
    regex: '\n[ \t]*\n[ \t]*[)}\]]'
    name: "Vertical Whitespace before Closing Braces"
    message: "Don't include vertical whitespace (empty line) before closing braces."
    severity: warning
